name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: sc4py - Lint with flake8 
      run: |
        cd sc4py \
        && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics \
        && flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: sc4py - Test with pytest and coverage
      run: |
        cd sc4py \
        && coverage run -m unittest tests/test_* \
        && coverage report -m
    - name: sc4net - Lint with flake8 
      run: |
        cd sc4net \
        && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics \
        && flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: sc4net - Test with pytest and coverage
      run: |
        cd sc4net \
        && coverage run -m unittest tests/test_* \
        && coverage report -m
